# Galaxy M51 config
DEVICE_MODEL_NAME="Galaxy M51"
DEVICE_ACTUAL_MODEL="SM-M515F"
CODENAME="m51"
PLATFORM="sd_7150"
DEVICE_VNDK_VERSION=30

# Stock firmware details for download
STOCK_MODEL="SM-A525F"
STOCK_CSC="EUX"
STOCK_IMEI="350281371234560"

# Source firmware details for download
MODEL="SM-S711U1"
CSC="AIO"
IMEI="358460181039276"

# Extra firmware which is optional
EXTRA_MODEL=""
EXTRA_CSC=""
EXTRA_IMEI=""

# Output
FILESYSTEM="erofs"
DEVICE_SUPER_PARTITION_SIZE=8053063680
DEVICE_SUPER_GROUP_BASIC_SIZE=8048869376

# Specs
DEVICE_HAVE_SPEN_SUPPORT=false
DEVICE_HAVE_QHD_PANEL=false
DEVICE_HAVE_HIGH_REFRESH_RATE=false
SUPPORT_HAPTIC_AUDIO_VIBRATOR=false
DEVICE_HAVE_ESIM_SUPPORT=false
DEVICE_HAVE_DUAL_SPEAKER=false
DEVICE_FINGERPRINT_SENSOR_TYPE="capacitive_powerkey_phone"

# Custom props (If not used , it will use values from stock rom)
DEVICE_SIOP_POLICY_FILENAME="siop_m51_sm7150"
DEVICE_DISPLAY_HFR_MODE="0"
DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ="60"
DEVICE_DEFAULT_REFRESH_RATE="60"
DEVICE_MDNIE_MODE="62481"
DEVICE_AUTO_BRIGHTNESS_LEVEL="3"
DEVICE_HAVE_DUAL_SPEAKER="false"

# Device specific
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_BRAND_NAME" "Galaxy M51"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_DEFAULT_FONT_SIZE" "3"
FF "SEC_FLOATING_FEATURE_SETTINGS_CONFIG_FCC_ID" "A3LSMM515F"
FF "SEC_FLOATING_FEATURE_SYSTEMUI_CONFIG_CORNER_ROUND" "2.0"
FF "SEC_FLOATING_FEATURE_LOCKSCREEN_CONFIG_PUNCHHOLE_VI" "face,pos:0.5:0.02292,size:0.1018:0.04583,type:circle"