name: Build AstroROM
run-name: Building ROM > ${{ inputs.device }}
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Choose device'
        required: true
        default: 'm51'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Free disk space (1/4) - System Junk
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/4) - Tool Cache
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Free disk space (3/4)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Free disk space (4/4)
        run: |
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/share/sbt
          sudo apt-get clean

      - name: Disk Space Check
        run: df -h /

      - name: Run AstroROM Build
        run: |
          sudo bash build.sh --build ${{ inputs.device }}
          
      - name: Uploading  ROM to SourceForge
        env:
          SF_M51_PATH: ${{ secrets.SF_M51_PATH }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SF_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          cd out
          ROM=$(ls *.zip | head -n 1)
          if [ -z "$ROM" ]; then
            echo "No ROM zip found!"
            exit 1
          fi          
          for ROM in SpiderGirl*.zip; do
            echo "Uploading $ROM to SourceForge..."
            scp -i ~/.ssh/id_rsa $ROM $SF_M51_PATH
          done
