name: Build CSC
run-name: Building ROM > ${{ inputs.device }}
on:
  workflow_dispatch:
    inputs:
      device:
        description: 'Choose objective'
        required: true
        default: ''
      upload_cloud:
        description: 'Upload ROM to cloud (PixelDrain)'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Free disk space (1/4) - System Junk
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force
          sudo docker builder prune -a

      - name: Free disk space (2/4) - Tool Cache
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Free disk space (3/4)
        uses: rokibhasansagar/slimhub_actions@main
        with:
          retain: 'compiler_cmake'

      - name: Free disk space (4/4)
        run: |
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/lib/node_modules
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/share/sbt
          sudo apt-get clean

      - name: Disk Space Check
        run: df -h /

      - name: Skip exiting
        run: |
            ASTROROM="/home/runner/work/CSC/CSC"
            find "$ASTROROM/astro" "$ASTROROM/scripts" -type f -name "*.sh" -exec \
            sed -i 's/exit[[:space:]]*1/exit 0/g' {} + 
            find "$ASTROROM/scripts" -type f -name "*.sh" -exec \
            sed -i 's/return[[:space:]]*1/return 0/g' {} +
            
      - name: Run AstroROM Build
        run: |
          sudo bash build.sh --build ${{ inputs.device }}


      - name: Download PixelDrain CLI (pd)
        if: ${{ inputs.upload_cloud }}
        run: |
          curl -L https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.6/pd_0.7.6_linux_amd64.tar.gz -o pd.tar.gz
          tar -xvf pd.tar.gz
          chmod +x pd
          sudo mv pd /usr/local/bin/pd
          
      - name: Upload ROM to PixelDrain
        if: ${{ inputs.upload_cloud }}
        env:
          PIXELDRAIN_API_KEY: ${{ secrets.PIXELDRAIN_API_KEY }}
        run: |
          cd out
          prism=$(ls prism.img | head -n 1)
          optics=$(ls optics.img | head -n 1)
          echo "Uploading $prism to PixelDrain..."
          pd --api-key "$PIXELDRAIN_API_KEY" upload "$prism" | sed 's|api/file|u|g'
          echo "Uploading $optics to PixelDrain..."
          pd --api-key "$PIXELDRAIN_API_KEY" upload "$optics" | sed 's|api/file|u|g'
